#!/usr/bin/env python3
"""
Alert Escalation for Maddrey Discriminant Function (mDF).
Triggers clinical alerts when scores cross critical thresholds,
escalates rapid score changes, and routes high-risk scores to specialists.
Author: Dr. Abu Suraih Sakhri
License: MIT
"""

import json
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass, field, asdict


@dataclass
class Alert:
    """A clinical alert generated by the escalation engine."""
    alert_id: str
    timestamp: str
    severity: str  # critical | warning | info
    category: str
    message: str
    patient_id: str
    mdf_score: float
    recommended_action: str
    escalation_target: Optional[str] = None
    acknowledged: bool = False


@dataclass
class EscalationRule:
    """Defines a rule for alert escalation."""
    rule_id: str
    name: str
    condition: str
    severity: str
    target: str
    message_template: str
    cooldown_hours: int = 24


class AlertEscalationEngine:
    """Engine for generating and managing mDF-based clinical alerts."""

    # Threshold constants
    MDF_CRITICAL_THRESHOLD = 32.0
    MDF_SEVERE_THRESHOLD = 54.0
    RAPID_CHANGE_THRESHOLD = 15.0  # mDF points change
    RAPID_CHANGE_DAYS = 3

    def __init__(self, patient_id: str):
        self.patient_id = patient_id
        self.alerts: List[Alert] = []
        self.score_history: List[Tuple[str, float]] = []  # (timestamp, score)
        self._alert_counter = 0

    def _next_alert_id(self) -> str:
        self._alert_counter += 1
        return f"ALERT-{self.patient_id}-{self._alert_counter:04d}"

    def evaluate_score(self, mdf_score: float, timestamp: Optional[str] = None) -> List[Alert]:
        """Evaluate a new mDF score and generate alerts as needed."""
        ts = timestamp or datetime.now().isoformat()
        self.score_history.append((ts, mdf_score))
        new_alerts = []

        # Rule 1: Critical threshold crossing
        if mdf_score >= self.MDF_CRITICAL_THRESHOLD:
            alert = Alert(
                alert_id=self._next_alert_id(),
                timestamp=ts,
                severity="critical",
                category="threshold_crossing",
                message=f"mDF score {mdf_score:.1f} >= {self.MDF_CRITICAL_THRESHOLD}. "
                        f"Patient meets criteria for corticosteroid therapy consideration.",
                patient_id=self.patient_id,
                mdf_score=mdf_score,
                recommended_action="Initiate prednisolone 40mg/day x 28 days. "
                                   "Obtain Lille score at day 7 to assess response.",
                escalation_target="hepatology",
            )
            new_alerts.append(alert)

        # Rule 2: Severe threshold
        if mdf_score >= self.MDF_SEVERE_THRESHOLD:
            alert = Alert(
                alert_id=self._next_alert_id(),
                timestamp=ts,
                severity="critical",
                category="severe_disease",
                message=f"mDF score {mdf_score:.1f} >= {self.MDF_SEVERE_THRESHOLD}. "
                        f"Severe alcoholic hepatitis with high short-term mortality risk.",
                patient_id=self.patient_id,
                mdf_score=mdf_score,
                recommended_action="Urgent hepatology consultation. Consider liver transplant evaluation. "
                                   "Assess for contraindications to steroids (active infection, GI bleeding).",
                escalation_target="transplant_hepatology",
            )
            new_alerts.append(alert)

        # Rule 3: Rapid score change
        if len(self.score_history) >= 2:
            prev_ts, prev_score = self.score_history[-2]
            prev_dt = datetime.fromisoformat(prev_ts)
            curr_dt = datetime.fromisoformat(ts)
            days_diff = (curr_dt - prev_dt).total_seconds() / 86400.0

            if days_diff <= self.RAPID_CHANGE_DAYS:
                score_change = abs(mdf_score - prev_score)
                if score_change >= self.RAPID_CHANGE_THRESHOLD:
                    direction = "increased" if mdf_score > prev_score else "decreased"
                    alert = Alert(
                        alert_id=self._next_alert_id(),
                        timestamp=ts,
                        severity="warning",
                        category="rapid_change",
                        message=f"mDF score {direction} by {score_change:.1f} points in {days_diff:.1f} days "
                                f"({prev_score:.1f} -> {mdf_score:.1f}).",
                        patient_id=self.patient_id,
                        mdf_score=mdf_score,
                        recommended_action="Urgent reassessment of clinical status. "
                                           "Evaluate for new complications (infection, GI bleed, renal failure).",
                        escalation_target="gi_consult",
                    )
                    new_alerts.append(alert)

        # Rule 4: Score below threshold after being above (treatment response)
        if len(self.score_history) >= 2:
            prev_ts, prev_score = self.score_history[-2]
            if prev_score >= self.MDF_CRITICAL_THRESHOLD and mdf_score < self.MDF_CRITICAL_THRESHOLD:
                alert = Alert(
                    alert_id=self._next_alert_id(),
                    timestamp=ts,
                    severity="info",
                    category="treatment_response",
                    message=f"mDF score improved from {prev_score:.1f} to {mdf_score:.1f}. "
                            f"Score now below corticosteroid threshold.",
                    patient_id=self.patient_id,
                    mdf_score=mdf_score,
                    recommended_action="Continue current treatment. Calculate Lille score at day 7 "
                                       "to confirm steroid response.",
                    escalation_target=None,
                )
                new_alerts.append(alert)

        # Rule 5: Overdue assessment check
        if len(self.score_history) >= 2:
            last_ts = self.score_history[-2][0]
            last_dt = datetime.fromisoformat(last_ts)
            curr_dt = datetime.fromisoformat(ts)
            days_since_last = (curr_dt - last_dt).total_seconds() / 86400.0
            if days_since_last > 7 and self.score_history[-2][1] >= self.MDF_CRITICAL_THRESHOLD:
                alert = Alert(
                    alert_id=self._next_alert_id(),
                    timestamp=ts,
                    severity="warning",
                    category="overdue_assessment",
                    message=f"Assessment overdue: {days_since_last:.0f} days since last mDF "
                            f"(was {self.score_history[-2][1]:.1f}).",
                    patient_id=self.patient_id,
                    mdf_score=mdf_score,
                    recommended_action="Obtain repeat labs (PT/INR, bilirubin) and recalculate mDF. "
                                       "Calculate Lille day-7 score if on corticosteroids.",
                    escalation_target="primary_team",
                )
                new_alerts.append(alert)

        self.alerts.extend(new_alerts)
        return new_alerts

    def get_active_alerts(self, severity: Optional[str] = None) -> List[Alert]:
        """Get unacknowledged alerts, optionally filtered by severity."""
        alerts = [a for a in self.alerts if not a.acknowledged]
        if severity:
            alerts = [a for a in alerts if a.severity == severity]
        return alerts

    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert by ID."""
        for alert in self.alerts:
            if alert.alert_id == alert_id:
                alert.acknowledged = True
                return True
        return False

    def get_escalation_summary(self) -> Dict[str, Any]:
        """Generate a summary of all alerts and escalations."""
        active = self.get_active_alerts()
        return {
            "patient_id": self.patient_id,
            "total_alerts": len(self.alerts),
            "active_alerts": len(active),
            "critical": len([a for a in active if a.severity == "critical"]),
            "warnings": len([a for a in active if a.severity == "warning"]),
            "info": len([a for a in active if a.severity == "info"]),
            "latest_score": self.score_history[-1][1] if self.score_history else None,
            "escalation_targets": list(set(a.escalation_target for a in active if a.escalation_target)),
            "alerts": [asdict(a) for a in active],
        }

    def export_alerts_json(self, output_path: str) -> None:
        """Export all alerts to JSON."""
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(asdict(self.get_escalation_summary()), f, indent=2, default=str)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Maddrey DF Alert Escalation Engine")
    parser.add_argument("--patient-id", default="PATIENT-001", help="Patient identifier")
    parser.add_argument("--scores", required=True, help="JSON file with list of {timestamp, mdf_score}")
    parser.add_argument("--output", default="alerts.json", help="Output alerts JSON")
    args = parser.parse_args()

    with open(args.scores, "r") as f:
        score_data = json.load(f)

    engine = AlertEscalationEngine(args.patient_id)
    for entry in score_data:
        engine.evaluate_score(entry["mdf_score"], entry.get("timestamp"))

    engine.export_alerts_json(args.output)
    summary = engine.get_escalation_summary()
    print(json.dumps(summary, indent=2, default=str))
